### ISSUE TITLE
Feature Request(s)

### ISSUE THREAD

**Issue by Neurotoxin001** [TDesktop-x64/tdesktop#1]
Hey, found your client and I'm amazed how many QoL features it's have.

Can I suggest you to add some more?

1. GIF's in Shared Media https://github.com/telegramdesktop/tdesktop/issues/1677
2. Ban and delete all messages when click on "user joined" message https://github.com/telegramdesktop/tdesktop/issues/6576
3. Remember last chosen date while schedule posts https://github.com/telegramdesktop/tdesktop/issues/7317
4. Add repost without author feature
5. Add "discuss" button when click on post in channel (like it's done on iOS) if channel have chat for discuss it

Because it's very long time to wait when official developers can add it to official client :/

**Comment by SmartManoj** [comment]
Why closed?
