### ISSUE TITLE
Cannot download videos and some photos

### ISSUE THREAD

**Issue by AlexKurisu** [TDesktop-x64/tdesktop#110]
### Steps to reproduce

1. Update to 64Gram ver 1.0.49
2. Try to view or download any video from channels
3. Enjoy the download never beginning
Example: ![image](https://user-images.githubusercontent.com/60626727/196035995-80ac0183-1f78-41df-8ff6-256444175cda.png)

### Expected behaviour

Should be able to watch videos just like before

### Actual behaviour

Video download never begins

### Operating system

GNU/Linux (Void Linux)

### Version of Telegram Desktop

64Gram 1.0.49 (TD 4.2.4)

### Installation source

Other (unofficial) source

**Comment by guglovich** [comment]
+1
Arch Linux + last client
