### ISSUE TITLE
[Feature Request] Increase the upload speed

### ISSUE THREAD

**Issue by tissole** [TDesktop-x64/tdesktop#117]
### Is your feature request related to a problem?

I would like to upload files (both small and large) at a higher speed.

### Describe the solution you'd like

Optimize the client to utilize the available bandwidth much better.

### Describe alternatives you've considered

None.

### Additional context

The last [attempt ](https://github.com/TDesktop-x64/tdesktop/commit/edf74453e048692734a0c432395b6482153a9378 )has failed, probably because of using wrong values. 512 is the [maximum ](https://core.telegram.org/api/files)accepted by Telegram
`FILE_PART_TOO_BIG: The size limit (512 KB) for the content of the file part has been exceeded`
Can you try again with this value (512)? Also, can you optimize the uploading of [small files](https://github.com/TDesktop-x64/tdesktop/blob/dev/Telegram/SourceFiles/storage/file_upload.cpp#L29)? (using same value -512- for all files regarding of their size?) You can also try increasing the sessions from 8 to 20. See [here ](https://gist.github.com/painor/7e74de80ae0c819d3e9abcf9989a8dd6#file-fasttelethon-py-L125). Thanks!

**Comment by c0re100** [comment]
My attempt is different thing...-__-
It's trying to increase the download speed, not upload speed...
and then upload speed boost already done it.

**Comment by tissole** [comment]
Yes, you're right, download speed. Still, the reason it caused trouble can be because of the bigger chunk size? Can upload be further improved for small files by increasing the chunk size, and for all the files by increasing the number of sessions? Can you make a separate branch, so users can run tests before merging in the main?

**Comment by c0re100** [comment]
> Yes, you're right, download speed. Still, the reason it caused trouble can be because of the bigger chunk size? Can upload be further improved for small files by increasing the chunk size, and for all the files by increasing the number of sessions? Can you make a separate branch, so users can run tests before merging in the main?

About download:
Yes, the bigger chunk size make client lead to unexpected crash.
Of cause there are no issue for download file, only happen on video playing.

About upload:
I can test it myself, 1000Mbps broadband user here.
But no luck, I have do some trick (include your said), so I guess it's server side limited.
