### ISSUE TITLE
Can't forward as copy to saved messages.

### ISSUE THREAD

**Issue by fosam** [TDesktop-x64/tdesktop#119]
### Steps to reproduce

Try to Forward message as a copy to saved message.

### Expected behaviour

Forward message as copy (Without sender's name) to saved messages.

### Actual behaviour

Can only forwatd message with sender's name.

In v1.0.52 it's possible to forward message as copy to saved messages, the problem is only in v1.0.53.

### Operating system

W10

### Version of Telegram Desktop

v1.0.53

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
I can't reproduce.
Need more info.

**Comment by fosam** [comment]
Can you try to forward a messages to your saved messages without the sender's name?

**Comment by c0re100** [comment]
> Can you try to forward a messages to your saved messages without the sender's name?

Yes, I did, but forward successfully.

**Comment by c0re100** [comment]
> Very strange, i don't get the option to hide sender's name, can you take a screenshot of the menu that let's hide the sender's name?

Right click `Send` button and untick sender name.
BTW Forward as copy option will be back in the next version

**Comment by fosam** [comment]
> Right click `Send` button and untick sender name.

There is no `send` button, and all forward options don't have the option to remove sender's name when sending to **saved messages.**

`Forward as copy` is the only option that removes the sender's name when sending to **saved messages.**

**Note:** i'm only talking about **saved messages** chat, sending to other chats without sender's name is working.

Thanks.
