### ISSUE TITLE
Translation line does not fit in the field

### ISSUE THREAD

**Issue by hooddy** [TDesktop-x64/tdesktop#123]
### Steps to reproduce

Run 64gram. Go to Settings, change language to Russian (possibly other languages have this issue). After rerun 64gram go to Enhanced Settings. Some option doesn't fit in filed and need line breaking.
![01](https://user-images.githubusercontent.com/6899176/204232613-e3369158-67c8-4251-835c-72ba2b3a60a7.png)

### Expected behaviour

All string must have line breaks.

### Actual behaviour

String outfits they fields. I dunno should I need to open this issue in official tdeskop github or bugs portal?

### Operating system

Windows 7 x 64

### Version of Telegram Desktop

1.0.56

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
Maybe you can help to translate it and make it shorter?
https://github.com/TDesktop-x64/Localization/commits/master/ru.json

**Comment by hooddy** [comment]
> Maybe you can help to translate it and make it shorter?
> https://github.com/TDesktop-x64/Localization/commits/master/ru.json

Oh my gush i didn't see your message im sorry. Sure ill check it.

**Comment by hooddy** [comment]
@c0re100 is it possible to insert a line breakline in translation string?

**Comment by c0re100** [comment]
> @c0re100 is it possible to insert a breakline in translation string?

impossible
