### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by intruder212** [TDesktop-x64/tdesktop#127]
### Steps to reproduce

Select some message

### Expected behaviour

Icons

### Actual behaviour

![image](https://user-images.githubusercontent.com/108568352/207140383-5304578c-f1f2-45ae-b6ea-74d8460a3cc6.png)

### Operating system

ArchLinux, 6.0.11-zen1-1-zen,Kde plasma

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by JasonKhew96** [comment]
install emoji font
