### ISSUE TITLE
[Feature Request] Add Smoooth Scrolling Option

### ISSUE THREAD

**Issue by AdishSagarawat** [TDesktop-x64/tdesktop#134]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

{Best if it will be like this}    https://webflow.com/made-in-webflow/website/Webflow-Smooth-Scroll-Luxyjs

{Good if it will be like }    Microsoft Edge Scrolling ....

### Describe alternatives you've considered

:)

**Comment by EryX0** [comment]
this.
there's no telegram desktop client which supports smooth scrolling with mouse other than Unigram which is UWP and its buggy as heck.
hoping we get a nice smooth scroll option on this client.
