### ISSUE TITLE
[Feature Request] Add option to show username or phone no. in of "Add emoji status"

### ISSUE THREAD

**Issue by AdishSagarawat** [TDesktop-x64/tdesktop#137]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/69076256/212055096-13749b75-ceb7-444a-bb0d-df80d09d92be.png)

It should be like this

![photo_2023-01-12_16-58-49](https://user-images.githubusercontent.com/69076256/212055496-83d97fb0-be26-4fd0-be99-8f5fa9734852.jpg)

### Describe alternatives you've considered

exteraGram Android

**Comment by AdishSagarawat** [comment]
![image](https://user-images.githubusercontent.com/69076256/212066854-43777df3-4579-40d7-825c-d890206d920b.png)

**Comment by tasi788** [comment]
click menu and scroll down
<img width="199" alt="image" src="https://user-images.githubusercontent.com/11913223/212070154-06a76168-b0a5-4fa0-a52d-dd9f07ea3e05.png">

**Comment by AdishSagarawat** [comment]
![image](https://user-images.githubusercontent.com/69076256/212307156-7d9f3af2-d439-48c1-8a7a-04a91fe9aa02.png)

@tasi788 See Even after enabling it's not working.

Also, I want to show username instead of phone number.
