### ISSUE TITLE
BUG : Hamburger Menu Button Turned Into Large Box !

### ISSUE THREAD

**Issue by AdishSagarawat** [TDesktop-x64/tdesktop#139]
### Steps to reproduce

Click on settings
Click on enhanced settings
Click on hide all chats folder toggle

### Expected behaviour

This should be like this:

![image](https://user-images.githubusercontent.com/69076256/212057248-a28f757f-bc96-4d01-939b-80b0392b5dbc.png)

### Actual behaviour

But it is like this:

![image](https://user-images.githubusercontent.com/69076256/212057375-bcafb64c-0a51-4e90-9a2d-b9a5983b8ded.png)

### Operating system

Windows 11

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by lucas-jooj** [comment]
You need to disable folders altogether if you want to hide that bar

**Comment by AdishSagarawat** [comment]
It's still there even after disable folders altogether.

I have to restart 64gram to fix.
