### ISSUE TITLE
[Feature Request] Add Mute Icon in Info Sidedbar

### ISSUE THREAD

**Issue by AdishSagarawat** [TDesktop-x64/tdesktop#140]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

.

### Describe alternatives you've considered

Kotatogram

### Additional context

Like this:

![image](https://user-images.githubusercontent.com/69076256/212057893-1c41fb9a-d9bf-4bd6-a7af-9b8edcbfe6a6.png)

**Comment by AdishSagarawat** [comment]
![image](https://user-images.githubusercontent.com/69076256/212058261-9ba832c8-5126-4746-b18c-0ae05d9dd085.png)

**Comment by lucas-jooj** [comment]
![image](https://user-images.githubusercontent.com/118740362/212220636-d17974b6-5ef0-46d8-af28-e5951d5880b8.png)
Seems redundant
