### ISSUE TITLE
[Feature Request] Add "View Profile"  to context menu

### ISSUE THREAD

**Issue by AdishSagarawat** [TDesktop-x64/tdesktop#141]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

.

### Describe alternatives you've considered

Kotatogram

### Additional context

![image](https://user-images.githubusercontent.com/69076256/212058529-849b4585-7f92-4468-a184-83fdc882c3a4.png)

**Comment by lucas-jooj** [comment]
Go to advanced>experimental settings and enable it
