### ISSUE TITLE
Update current audio output

### ISSUE THREAD

**Issue by lemiosa** [TDesktop-x64/tdesktop#16]
### Steps to reproduce
1. Open app. Headphones is default audio output in system.
2. Change output to another device (TV, speaker etc).
3. No sound in new device (still hear it via headphones)
4. Restart app. Now I can hear a sound via new device.

**Comment by c0re100** [comment]
Can you reproduce with official telegram desktop?
If yes, you should create bug report to tdesktop upstream...
https://github.com/telegramdesktop/tdesktop/issues

**Comment by lemiosa** [comment]
> Can you reproduce with official telegram desktop?
> If yes, you should create bug report to tdesktop upstream...
> https://github.com/telegramdesktop/tdesktop/issues

hi, it works in latest version of the official app..

**Comment by c0re100** [comment]
> > Can you reproduce with official telegram desktop?
> > If yes, you should create bug report to tdesktop upstream...
> > https://github.com/telegramdesktop/tdesktop/issues
> 
> hi, it works in latest version of the official app..

Tested, but I can't reproduce this issue in x64 or official app...
I can hear a sound immediately when I change output to loudspeaker.

**Comment by lemiosa** [comment]
> > > Can you reproduce with official telegram desktop?
> > > If yes, you should create bug report to tdesktop upstream...
> > > https://github.com/telegramdesktop/tdesktop/issues
> > 
> > 
> > hi, it works in latest version of the official app..
> 
> Tested, but I can't reproduce this issue in x64 or official app...
> I can hear a sound immediately when I change output to loudspeaker.

Yeah, I understand why, maybe you change headphones & speaker with embedded sound card. When I use external sound card (usb connected) or my sound system (via usb) I need to restart an app. With the official app there's no problem..
