### ISSUE TITLE
There is a problem with the 2x speed function

### ISSUE THREAD

**Issue by hqlak47** [TDesktop-x64/tdesktop#172]
### Steps to reproduce

There is a problem with the 2x speed function. I have turned on 2x, and every time I open a new video, it plays at 1x speed, but it shows 2x incorrectly. Only when I manually click 2x to switch to 1x, and then click 1x to switch to 2x can I use the double speed function normally

### Expected behaviour

The double speed function should be enabled correctly

### Actual behaviour

Opening the video only has 1x speed, even though I previously modified it to 2x, this issue still occurs at other speeds

### Operating system

win10 22h2 lastest

### Version of Telegram Desktop

v1.0.88 (TDesktop v4.8.10)

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
It's tdesktop bug and it's fixed
