### ISSUE TITLE
Pin button isn't working

### ISSUE THREAD

**Issue by LWJerri** [TDesktop-x64/tdesktop#175]
### Steps to reproduce

1. Open chat in the new chat window.
2. Try to pin chat.

### Expected behaviour

Chat must be pinned on the screen after click on pin button.

### Actual behaviour

Chat must be pinned on the screen, but it's not happening.

### Operating system

Windows 11

### Version of Telegram Desktop

64Gram Desktop v1.0.88 x64 (v4.8.10)

### Installation source

Other (unofficial) source

**Comment by LWJerri** [comment]
This issue also related to https://github.com/TDesktop-x64/tdesktop/issues/50.

**Comment by c0re100** [comment]
Won't fix until forkgram fix it.
https://github.com/forkgram/tdesktop/issues/104
