### ISSUE TITLE
Improved delivery for Linux

### ISSUE THREAD

**Issue by Zalexanninev15** [TDesktop-x64/tdesktop#176]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Creating packages for at least the basic "basics" of Linux in the form of Debian/Fedora - deb, rpm. Or creating a flatpak package to install on any Linux.

### Describe alternatives you've considered

Using the archive from the release is not very convenient and does not integrate well into the "menu", for example in GNOME, or there may be problems with startup.

**Comment by watzon** [comment]
Started working on a Flatpak based on the official Telegram Flatpak, but unfortunately this seems to have a more difficult Linux build process than the official Telegram app.

**Comment by tehcneko** [comment]
Flatpak builds are now available at Flathub:
https://flathub.org/apps/io.github.tdesktop_x64.TDesktop
