### ISSUE TITLE
Can't download large media or files

### ISSUE THREAD

**Issue by devintly** [TDesktop-x64/tdesktop#185]
### Steps to reproduce

1. Enable speedboost download enhanced option

### Expected behaviour

Normal

### Actual behaviour

Error (Can't download large media or files)

### Operating system

Windows 10

### Version of Telegram Desktop

1.0.93 (issue started from 1.0.92)

### Installation source

Other (unofficial) source

**Comment by c0re100** [comment]
https://t.me/tg_x64/895

**Comment by devintly** [comment]
> https://t.me/tg_x64/895

I tried this, also tried to clear reinstall. Still don't work for me. Maybe it is because i'm on portable version?
