### ISSUE TITLE
Very fast scrolling in the chat list

### ISSUE THREAD

**Issue by f242** [TDesktop-x64/tdesktop#187]
### Steps to reproduce

program interface scale 220%
In 3 mouse wheel steps I have one screen almost completely scrolling from bottom to up, it's very fast
0  |  1  |  2  |  3
🟢🟢🟢🟢
🟢🟢🟢🔴
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🔴🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🔴🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🔴🟢🟢🟢

### Expected behaviour

about twice as slow

### Actual behaviour

very fast

### Operating system

win 11, 200% ui scale

### Version of Telegram Desktop

1.0.95 x64

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26546#issuecomment-1675151212
