### ISSUE TITLE
[BUG] autostart flag for autostart via flatpak

### ISSUE THREAD

**Issue by xz-dev** [TDesktop-x64/tdesktop#188]
### Steps to reproduce

1. cp desktop file from `~/.local/share/flatpak/app/io.github.tdesktop_x64.TDesktop/current/active/export/share/applications/io.github.tdesktop_x64.TDesktop.desktop` to `~/.config/autostart/`
2. change `Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=telegram-desktop --file-forwarding io.github.tdesktop_x64.TDesktop -autostart` as Telegram

### Expected behaviour

1. autostart when boot and automatically minimize to tray
2. Or if I run `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=telegram-desktop --file-forwarding io.github.tdesktop_x64.TDesktop -autostart` manually, it will start and automatically minimize to tray

### Actual behaviour

Nothing happened

### Operating system

Gentoo 2.14 x86_64(Flatpak 1.14.4)

### Version of Telegram Desktop

64Gram Desktop 1.0.95 | v4.9.9

### Installation source

Flatpak

**Comment by tehcneko** [comment]
为什么要复制？设置里不是有开机自启选项吗？

**Comment by xz-dev** [comment]
It notify `Could not register for autostart`

**Comment by tehcneko** [comment]
> > 为什么要复制？设置里不是有开机自启选项吗？
> 
> It notify `Could not register for autostart`

Please fix your system
