### ISSUE TITLE
[BUG] Can't schedule a forward message (W/O quote)

### ISSUE THREAD

**Issue by JasonKhew96** [TDesktop-x64/tdesktop#19]
Can't schedule a forward message (W/O quote)

### Steps to reproduce
1. Forward message (W/O quote)
2. Select a target chat
3. Right click the send button and schedule

### Expected behaviour
Message should be scheduled.

### Actual behaviour
Message send immediately

### Configuration
**Operating system:**
Ubuntu Linux 20.04

**Version of Telegram Desktop:**
2.4.15.1 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases

**Used theme**:
-

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by c0re100** [comment]
Will be fixed in the next Beta :P

**Comment by c0re100** [comment]
Fixed in v2.5.6.1 Beta
