### ISSUE TITLE
Squares instead of emoji

### ISSUE THREAD

**Issue by winqooq** [TDesktop-x64/tdesktop#2]
### Steps to reproduce
1. Highlight message

### Expected behaviour
Action buttons with messages are distinguishable

### Actual behaviour
![Squares instead of emoji](https://user-images.githubusercontent.com/55299850/92537939-101a1a00-f246-11ea-9dda-d252533ccc37.png)
When you highlight a message, squares appear in the bar instead of emoji.

### Configuration
Windows 7 Ultimate x64 (7601)
Telegram Desktop x64 v2.3.2.1

P,S: offer:
Replace emoji on buttons, with icons
![test_icon](https://user-images.githubusercontent.com/55299850/92539918-a997fa80-f24b-11ea-81ed-1490d9d55845.png)

**Comment by c0re100** [comment]
Since windows 7 do not have newest Unicode set(Segoe UI Symbol), so squares appear in your tdesktop.....
But I don't want to deal with TDesktop UI (emoji change to icon) :'(
So, you can enable `Show Emoji Button As Text` option in Enhanced Setting to solve this problem.
*Version >= 2.4.3.1 only*
