### ISSUE TITLE
Telegram v2.5.1.1 Windows 7_x64 problem update

### ISSUE THREAD

**Issue by CoalaDePorsche** [TDesktop-x64/tdesktop#20]
Desktop-x64 has an error that gave me problems, I trusted the update system of the application and when I updated to version Telegram v2.5.1.1 my telegram simply does not open anymore

and I can't make a clean installation because I can't give an error either

my system is: Windows 7_x64

https://user-images.githubusercontent.com/68451871/103103628-1f5c8200-4601-11eb-98a6-02372705b873.mp4

**Comment by c0re100** [comment]
Known issue.
Will be fixed on the next version. :'(

**Comment by c0re100** [comment]
Can you try those build?
https://github.com/TDesktop-x64/tdesktop/releases/download/v2.5.1.1/Telegram_2.5.1.1_x64_rebuild.zip
https://github.com/TDesktop-x64/tdesktop/releases/download/v2.5.1.1/Telegram_2.5.1.1_x86_rebuild.zip

**Comment by CoalaDePorsche** [comment]
everything is ok in this update, thank you very much for fixing the error.

**Comment by j9o1** [comment]
> Can you try those build? and report the result here :)
> https://github.com/TDesktop-x64/tdesktop/releases/download/v2.5.1.1/Telegram_2.5.1.1_x64_rebuild.zip
> https://github.com/TDesktop-x64/tdesktop/releases/download/v2.5.1.1/Telegram_2.5.1.1_x86_rebuild.zip

Had a weird issue about some libcrypto dll missing whenever I opened v2.5.1.1 on Windows 8.1 but this rebuild fixed it, thank you so much!
