### ISSUE TITLE
[Question] Should unmodified builds use the same api id&hash as yours?

### ISSUE THREAD

**Issue by KspLite** [TDesktop-x64/tdesktop#21]
Hello. I intend to maintain an AUR package of TDesktop-x64. Telegram allowed archlinux to build their package with the official api id&hash. So I'm wondering whether I should use your api id&hash directly to build mine.

**Comment by c0re100** [comment]
No need :) 
Cause current x64 API ID&Hash isn't mine.

**Comment by KspLite** [comment]
Thanks for your reply. I'll just use the official api id&hash.

**Comment by KspLite** [comment]
I'm here with the same question again since 64Gram has a different pair of API ID&Hash. XD
