### ISSUE TITLE
[Feature Request] Option to change sticker size in chat

### ISSUE THREAD

**Issue by Daksh777** [TDesktop-x64/tdesktop#22]
### Is your feature request related to a problem?
Currently, the size of stickers in the chat look very large and take a lot of space. An option to change the sticker size would be great to deal with this problem. (An option to change sticker size is also present in Kotatogram)

### Describe the solution you'd like
Implement an option to change sticker size in chat.

### Describe alternatives you've considered
Kotatogram's option to change sticker size

### Additional context
Screenshot from Kotatogram:
![image](https://user-images.githubusercontent.com/43648146/106851851-fb4e8f00-66dc-11eb-9b85-59ede45a4d97.png)

**Comment by sudo-nautilus** [comment]
will be great

**Comment by 66Leo66** [comment]
PLEASE MAKE THIS PLZ
