### ISSUE TITLE
Virus in 2.5.9.1 x64

### ISSUE THREAD

**Issue by RubensRainelli** [TDesktop-x64/tdesktop#27]
Virus in this release:
https://github.com/TDesktop-x64/tdesktop/releases/download/v2.5.9.1/Telegram_2.5.9.1_x64.zip

Report: 
Trojan:Script/Wacatac.B!ml

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503

**Comment by c0re100** [comment]
https://t.me/tg_x64_chat/2633
