### ISSUE TITLE
[Feature Request] macOS Builds?

### ISSUE THREAD

**Issue by dotvhs** [TDesktop-x64/tdesktop#3]
Would it be possible to provide macOS build for this lovely project? I could help testing them.

**Comment by c0re100** [comment]
Here you go 
https://github.com/TDesktop-x64/tdesktop/releases/download/v2.4.2.1/Telegram.2.4.2.1_mac.dmg

**Comment by dotvhs** [comment]
Thank you! Will play with it :)
