### ISSUE TITLE
When forwarding without quotes files lose their order

### ISSUE THREAD

**Issue by tissole** [TDesktop-x64/tdesktop#30]
### Steps to reproduce
 A user is forwarding without quotes 40-50 files that were numbered as 1,2,3...50 in the source channel.

### Expected behaviour
Tell us what should happen
Files should be forwarded exactly as they were ordered in the source channel.
### Actual behaviour
Tell us what happens instead
Files are copied unordered 1.4.8.15.5.10...etc This behaviour occurs quite frequently.
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.7.4.1x64

**Comment by c0re100** [comment]
I think it is unfixable.
It look like the order of message is handled by server, cause `forwarding without quotes` is forward one by one already...
Just like you said, select 1,2,3...50, then 64Gram sent 1,2,3...50 one by one to another chat.
And most important thing, the order of receive message may be random order.
You can enable "Show message ID" in Enhanced Settings to check an message id.
