### ISSUE TITLE
classic forward is unable to use

### ISSUE THREAD

**Issue by Ben-md5** [TDesktop-x64/tdesktop#32]
### Steps to reproduce
1. use classic forward
2. 
3. 

### Expected behaviour
classic forward is able to use

### Actual behaviour
classic forward is unable to use

### Configuration
**win11 21H2:**

**Version of Telegram Desktop:**
2.9.3.1 64
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by c0re100** [comment]
It will be fixed in the next version.
