### ISSUE TITLE
[Feature Request] How about custom font ?

### ISSUE THREAD

**Issue by lilyblessing** [TDesktop-x64/tdesktop#35]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

custom font

### Describe the solution you'd like

Are there any plans to support changing the default font? I really like 64gram, but the default font looks uncomfortable and I just want to replace it. If I could customize the font maybe I wouldn't need to use mactype.
(like kotatogram do that ?)

**Comment by TigerBeanst** [comment]
Use [https://github.com/ysc3839/FontMod](https://github.com/ysc3839/FontMod)

**Comment by txyyh** [comment]
> Use https://github.com/ysc3839/FontMod

It can't use on Linux and macOS

**Comment by Kyogre** [comment]
same issue as in https://github.com/TDesktop-x64/tdesktop/issues/60
