### ISSUE TITLE
[Feature Request] disable link open warning

### ISSUE THREAD

**Issue by soredake** [TDesktop-x64/tdesktop#36]
### Is your feature request related to a problem?

Would be nice to have option to disable this warning when opening url

![изображение](https://user-images.githubusercontent.com/5204968/136911501-fc73786e-c440-43b4-a4a9-93dcfb588974.png)

### Describe the solution you'd like

Having option to disable this.

### Describe alternatives you've considered

Hmmm....

**Comment by c0re100** [comment]
Link warning only happen on Markdown style URL.
I think it's not good for disabling this warning actually.
Cause if spammer posted phishing link with markdown, an user may be false click :'(
Let's say:
Spammer posted: `aaa.xyz` (I assume it's a virus website)
After aaa.xyz with Markdown
`aaa.xyz` » `normal.sites`
Can you guess what happens next?

**Comment by soredake** [comment]
> Link warning only happen on Markdown style URL.
> I think it's not good for disabling this warning actually.
> Cause if spammer posted phishing link with markdown, an user may be false click :'(
> Let's say:
> Spammer posted: `aaa.xyz` (I assume it's a virus website)
> After aaa.xyz with Markdown
> `aaa.xyz` » `normal.sites`
> Can you guess what happens next? 

I'm asking for an option, so i can decide for myself if this is worth the risk. It's too annoying for me.

**Comment by c0re100** [comment]
https://github.com/TDesktop-x64/tdesktop/releases/tag/v1.0.1

**Comment by soredake** [comment]
Thanks!
