### ISSUE TITLE
[Feature Request] Make Windows installer run on Windows 11 arm64

### ISSUE THREAD

**Issue by hathlife** [TDesktop-x64/tdesktop#37]
### Is your feature request related to a problem?

Currently the installer cannot run on Windows 11 arm64 devices , says "x64 system support only". However  the archive version runs great even with x64 emulation. 

### Describe the solution you'd like

Use isWoW64Process2() to determine if installer itself is running on a WoA x64 emulation layer.

### Describe alternatives you've considered

no idea

**Comment by c0re100** [comment]
I guess I need to add `arm64` here to allow installer run on arm64 devices,
But I don't have Windows arm64 devices, so I can't test
https://github.com/TDesktop-x64/tdesktop/blob/dev/Telegram/build/setup.iss#L36

**Comment by hathlife** [comment]
![image](https://user-images.githubusercontent.com/19867269/141651983-d0223d5a-6b70-4395-b21c-923266a5c12d.png)
It works
