### ISSUE TITLE
[Question] The icon of the group admins list button in the top bar is confusing

### ISSUE THREAD

**Issue by Rongronggg9** [TDesktop-x64/tdesktop#44]
The icon of the group admins list button in the top bar is confusing. It is much more like a favorite button. I could hardly imagine that it is a button to display the group admins list when I first saw this...
![](https://user-images.githubusercontent.com/15956627/148039965-bc9d196c-2aae-407e-8de6-709285927651.png)

I think it would be better if this icon could be replaced by the administrators icon.
![](https://user-images.githubusercontent.com/15956627/148041046-3a579aea-c07c-4aaa-a967-068231f261bf.png)

**Comment by c0re100** [comment]
Change in the next version.
