### ISSUE TITLE
Forward as Copy not working to Channels

### ISSUE THREAD

**Issue by JohnCale47** [TDesktop-x64/tdesktop#48]
### Steps to reproduce

Right click > Forward > Forward as Copy

### Expected behaviour

Copy File without sender name to Channel

### Actual behaviour

Can't forward file as copy to a Channel , its working for groups but for some reason cant forward as copy to channels .

### Operating system

Windows 10

### Version of Telegram Desktop

1.0.6 v3.4.3

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
Yes, known bug, fixed version soon

**Comment by c0re100** [comment]
Fixed in v1.0.7
https://github.com/TDesktop-x64/tdesktop/releases/tag/v1.0.7
