### ISSUE TITLE
[Feature Request] Regarding Repeat Feature

### ISSUE THREAD

**Issue by SmartManoj** [TDesktop-x64/tdesktop#5]
![image](https://user-images.githubusercontent.com/7231077/95820507-d4430a80-0d45-11eb-90d6-e5d62680becd.png)
For the first one, we should send the link to the post. Any use case for that?
For the second one, keep the same behavior but send it as new instead of reply and delete the original message. 
(Repeat & Delete)

Also, add on option for Forward & Delete

**Comment by 70akaline** [comment]
repeating another message in group chat is highly desired in a specific group of people

**Comment by c0re100** [comment]
As @70akaline said.
Btw option will move to Enhanced setting later.

**Comment by SmartManoj** [comment]
@70akaline but people joined after the message won't know that it is a repeated one. And for other members like me who read only mentioned message won't know.

**Comment by bestpika** [comment]
@SmartManoj So you don't think anyone is going to repeat sentences?

**Comment by SmartManoj** [comment]
@bestpika From @70akaline message, it is already happening and this option would encourage them to do more which is not good.

**Comment by bestpika** [comment]
@SmartManoj Please don't impose your values on others.

**Comment by tasi788** [comment]
@SmartManoj It's kind a feature from this third version, if you don't have a better opinion or you just want "discuss" about this function, don't use [Feature Request].

**Comment by SmartManoj** [comment]
@c0re100 

> [Feature Request] Also, add on option for Forward & Delete
