### ISSUE TITLE
can't pin 64gram's window

### ISSUE THREAD

**Issue by Ben-md5** [TDesktop-x64/tdesktop#50]
### Steps to reproduce

the pin buttom at the corner is useless now

### Expected behaviour

the pin buttom at the corner is optional

### Actual behaviour

the pin buttom at the corner is useless now

### Operating system

win11

### Version of Telegram Desktop

1.0.9 beta

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
Can you try 1.0.10 beta?

**Comment by Ben-md5** [comment]
> Can you try 1.0.10 beta?
not solve in 1.0.10 beta

**Comment by c0re100** [comment]
> > Can you try 1.0.10 beta?
> > not solve in 1.0.10 beta

Did you know which version's pin to top is working on Win11?
I am still using Win10 lol

**Comment by Ben-md5** [comment]
v 1.05

**Comment by c0re100** [comment]
I just tested Forkgram (Pin to top source code from forkgram) , and got same issue lol
So I think we need to forkgram fix it...

**Comment by Ben-md5** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        ？！interesting
        
    
        
            
        
    
    
        
        

        
    

    On 2/12/2022 ***@***.***> wrote： 



I just tested Forkgram (Pin to top source code from forkgram) , and got same issue lol
So I think we need to forkgram fix it...

**Comment by LWJerri** [comment]
+1, still not working.
