### ISSUE TITLE
[Feature Request] open recent chats (in bottom) and most communicated users (in top) when clicking on search menu on main screen

### ISSUE THREAD

**Issue by fsheidaiee** [TDesktop-x64/tdesktop#55]
### Is your feature request related to a problem?

Hi
in unigram client when tapping or clicking or openin search menu, it automatically opens recent chats and most communicated users.

### Describe the solution you'd like

like the one in unigram client

### Describe alternatives you've considered

android client has this feature too.

### Additional context

Please add this feature.
thanks

**Comment by c0re100** [comment]
Recent chats record related to local database, so it's impossible to implement on tdesktop :'(
