### ISSUE TITLE
Message text all variable symbol

### ISSUE THREAD

**Issue by lhj5426** [TDesktop-x64/tdesktop#56]
![image](https://user-images.githubusercontent.com/30548000/153728805-48730034-313e-4b7e-8412-08ff40d9ec55.png)
Just now, after updating the latest version of text messages, all of them have become like this

**Comment by c0re100** [comment]
Please update again, fixed now.

**Comment by lhj5426** [comment]
> Please update again, fixed now.

Thanks for fixing it
![image](https://user-images.githubusercontent.com/30548000/153729197-bd00db15-6902-42d9-bad7-e4ab8e6d4ba8.png)
