### ISSUE TITLE
[Feature Request] Flatpak Package?

### ISSUE THREAD

**Issue by Remik1r3n** [TDesktop-x64/tdesktop#65]
### Is your feature request related to a problem?

Not a problem

### Describe the solution you'd like

https://flatpak.org/

From Wikipedia: Flatpak is a utility for software deployment and package management for Linux. It is advertised as offering a sandbox environment in which users can run application software in isolation from the rest of the system.

Since Flatpak is cross-distro and powerful, It will great if there's a official package with Flatpak.

### Describe alternatives you've considered

no

**Comment by soredake** [comment]
Original tdesktop exists as flatpak package https://github.com/flathub/org.telegram.desktop, so we just need someone who fill use this repo as starting point.

**Comment by tehcneko** [comment]
Flatpak builds are now available at Flathub:
https://flathub.org/apps/io.github.tdesktop_x64.TDesktop
