### ISSUE TITLE
[Feature request] Link the letters: F,C,D to shortcuts whenever something is selected.

### ISSUE THREAD

**Issue by old-izayoi** [TDesktop-x64/tdesktop#7]
Example: 1. select msg
 2. press F and it forwards 
and like that with every possible function shown above, when something is selected

**Comment by c0re100** [comment]
Maybe `ALT+F` and `ALT+C` better...
I don't want to deal with TDesktop Custom UI widget LOL.
I'm trying to add new shortcut key`F`.
But sadly........
Forward widget can't type `F` and `C` in search field :'(

**Comment by old-izayoi** [comment]
> Maybe `ALT+F` and `ALT+C` better...
> I don't want to deal with TDesktop Custom UI widget LOL.
> I'm trying to add new shortcut key`F`.
> But sadly........
> Forward widget can't type `F` and `C` in search field :'(

yeah, alt+f and alt+c would be great too

**Comment by c0re100** [comment]
Available on v2.4.4.1
