### ISSUE TITLE
User avatars cannot be viewed in groups

### ISSUE THREAD

**Issue by free4537** [TDesktop-x64/tdesktop#76]
### Steps to reproduce

Example: user with id 1977546822 in the group @yxbjx（It seems that all users who have not set a username are unable to view the avatar）

### Expected behaviour

can view user avatar

### Actual behaviour

User avatars cannot be viewed in groups

### Operating system

win7 x64

### Version of Telegram Desktop

64Gram v1.0.27

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
Telegram server issue, not 64Gram bug.
