### ISSUE TITLE
Image shows in part

### ISSUE THREAD

**Issue by lekoOwO** [TDesktop-x64/tdesktop#77]
### Steps to reproduce

1. Connect 2 monitors to the PC, the A monitor is 4K (DPI 200%), the B monitor is 1080p (DPI 100%)
2. Open 64Gram in the B monitor with 125% Scale
3. Open a image

### Expected behaviour

Shows image normally

### Actual behaviour

![image](https://user-images.githubusercontent.com/20151124/163393927-bcbc1ace-20e6-4c16-91d3-a6fa1d7c8946.png)
Shows the image in the A monitor in the left upper corner (about 25% area), the image is cropped.

### Operating system

Windows 11 x64 21H2

### Version of Telegram Desktop

1.0.27 x64

### Installation source

Static binary from official website

**Comment by lekoOwO** [comment]
Fixed with this option
![image](https://user-images.githubusercontent.com/20151124/163395067-b6a18b76-447b-4162-86af-e6ebecf7b06c.png)

**Comment by c0re100** [comment]
Known: upstream UI bug :'(
