### ISSUE TITLE
[Feature Request] Add string names if it is already present for better translation

### ISSUE THREAD

**Issue by SmartManoj** [TDesktop-x64/tdesktop#8]
https://t.me/TranslationsTalk/5296?single

Here gifs and supergroups are not translated but they have string names.

**Comment by tasi788** [comment]
due to no more info, close issue.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/96070137-42f6a400-0ebd-11eb-9763-8c9d797429e4.png)
![image](https://user-images.githubusercontent.com/7231077/96070152-468a2b00-0ebd-11eb-8064-369c32774664.png)

**Comment by tasi788** [comment]
@SmartManoj I didn't see any problem on my machine, tested by using other telegram translate string,
![image](https://user-images.githubusercontent.com/11913223/96070334-90c9d700-0ed2-11eb-811a-c3b06377b0a5.png)
![image](https://user-images.githubusercontent.com/11913223/96070344-94f5f480-0ed2-11eb-88dd-67576b806b51.png)

**Comment by SmartManoj** [comment]
Can you check the exact string using
https://t.me/setlanguage/stringnames

**Comment by tasi788** [comment]
> Can you check the exact string using
> https://t.me/setlanguage/stringnames

obviously it that provider did bad work on it, please consider to use others provider.

**Comment by tasi788** [comment]
FYI. https://translations.telegram.org/stringnames/tdesktop/chat_list/

**Comment by SmartManoj** [comment]
> @SmartManoj I didn't see any problem on my machine, tested by using other telegram translate string.
> ![image](https://user-images.githubusercontent.com/11913223/96070334-90c9d700-0ed2-11eb-811a-c3b06377b0a5.png)
> ![image](https://user-images.githubusercontent.com/11913223/96070344-94f5f480-0ed2-11eb-88dd-67576b806b51.png)

How 'gifs' is changed to '{char}Gifs'

**Comment by c0re100** [comment]
FYI: https://github.com/TDesktop-x64/tdesktop#localization
