### ISSUE TITLE
64Gram crashing on opening since yesterday 

### ISSUE THREAD

**Issue by missemily2022** [TDesktop-x64/tdesktop#84]
### Steps to reproduce

Start the Application

### Expected behaviour

It should start

### Actual behaviour

![image](https://user-images.githubusercontent.com/97376138/174425757-1a2dec8b-625a-468a-8b25-8cae0a4c577d.png)

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

1000036 beta

### Installation source

Static binary from official website

### Logs

```shell
ApiId: 3722065
Assertion: "_localKey == nullptr" storage_domain.cpp:92
Binary: Telegram.exe
Launched: 18.06.2022 11:54:56
Platform: Windows64Bit
UserTag: ac0197ce74ea46
Version: 1000036 beta
Memory-usage: 98 MB (peak), 98 MB (current)
Pagefile-usage: 103 MB (peak), 102 MB (current)

Caught signal 11 (SIGSEGV) in thread 10404

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 7096
Minidump: 7adaecc1-3951-4c1d-bda7-d4a33a8d9f28

Backtrace omitted.
```

**Comment by c0re100** [comment]
Rollback to 1.0.34

**Comment by missemily2022** [comment]
@c0re100 How do I roll back? The application is not even starting

**Comment by thesleever** [comment]
@missemily2022 install older version in the directory of 64gram
also, how many accounts do you have?

**Comment by missemily2022** [comment]
@thesleever I have 7 accounts added
I installed an older version 
The application started but then it stuck at the below position
![image](https://user-images.githubusercontent.com/97376138/174434611-9dd593e4-7561-4dd5-be79-fe111edb3bf3.png)
