### ISSUE TITLE
[Bug] Generic Wayland Icon When Launched

### ISSUE THREAD

**Issue by ghost** [TDesktop-x64/tdesktop#85]
### Steps to reproduce

1. Switch to Wayland Session on KDE
2. Launch 64Gram Desktop

### Expected behaviour

It should display the telegram icon instead of generic wayland icon on KDE (Wayland)

### Actual behaviour

It showing generic wayland icon when launched.
BTW launching it with `QT_QPA_PLATFORM=xcb telegram-desktop` shows the icon when launched. But brokes so many features and UI sometimes. I mean sometimes the UI is not responding at all and even crashed. BTW its working fine when switched to X11 session on KDE

### Operating system

Arch Linux (KDE)

### Version of Telegram Desktop

Latest 1.0.36 (BTW facing this from a long ago)

### Installation source

Static binary from official website

**Comment by alexjp** [comment]
You can get a telegram icon (or any other icon if you want), if you create a specific .desktop file (you can use the telegram one as a template, and just replace the executable).

Then you need to set this (i am using the linux release build):
```
StartupWMClass=appimagekit_e6ef50ea65ba10a2e73711d30987006b-64gram_desktop
```

And it will show the telegram icon on the KDE taskbar.
