### ISSUE TITLE
[Question] 1.90 Gb file always fails to upload, they changed the Max File Size? 

### ISSUE THREAD

**Issue by ZeroCool22** [TDesktop-x64/tdesktop#86]
Till some minutes ago i was able to Upload files without problems, now i can't...

They are doing it so ppl buy Premium Plan?

**Comment by ZeroCool22** [comment]
Damn, even a 1.60 Gb file failed...

**Comment by missemily2022** [comment]
@ZeroCool22 It may be your Internet Connectivity Issue
Telegram will never do any such thing which disturbs their free users
