### ISSUE TITLE
[Feature Request] Windows ARM64 build

### ISSUE THREAD

**Issue by ryank231231** [TDesktop-x64/tdesktop#95]
### Is your feature request related to a problem?

Currently 64Gram do not have a ARM64 build, please provide ARM64 build for better performance.

### Describe the solution you'd like

Provide ARM64 builds for 64Gram.

### Describe alternatives you've considered

Nothing.

**Comment by c0re100** [comment]
Telegram Desktop do not support Windows ARM64.
