### ISSUE TITLE
Improving video bitrate streaming?

### ISSUE THREAD

**Issue by zakiloki0** [TDesktop-x64/tdesktop#96]
It's is possible or depends only on Telegram server side?

Thanks for your work.

**Comment by c0re100** [comment]
What is your mean?
You mean user's uploaded video?
Then impossible.

**Comment by zakiloki0** [comment]
> What is your mean? You mean user's uploaded video? Then impossible.

No, I mean stream a video, a live stream.

**Comment by c0re100** [comment]
> > What is your mean? You mean user's uploaded video? Then impossible.
> 
> No, I mean stream a video, a live stream.

rtmp live stream depends on Telegram server side.
